[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/cargopete/balerion"
rust-version = "1.85"

[workspace.dependencies]
balerion-bt = { path = "crates/balerion-bt", version = "0.1.0" }
balerion-ia = { path = "crates/balerion-ia", version = "0.1.0" }
balerion-index = { path = "crates/balerion-index", version = "0.1.0" }
balerion-tpb = { path = "crates/balerion-tpb", version = "0.1.0" }
balerion-web = { path = "crates/balerion-web", version = "0.1.0" }

anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time", "sync"] }
tracing = "0.1"
