#!/usr/bin/env bash
# Keep the player running on a machine that is always on, reachable by your own
# devices and nobody else's.
#
#   ./ops/install-player-linux.sh
#
# Undo with:
#
#   systemctl --user disable --now balerion-serve
#   rm ~/.config/systemd/user/balerion-serve.service ~/.config/balerion/serve.env
#
# The macOS equivalent is install-player.sh. This one differs in two ways that
# are not cosmetic: it binds to the network rather than to loopback, because the
# point of an always-on machine is that a phone can reach it, and it therefore
# generates a token, because the endpoint it exposes downloads whatever magnet
# it is handed.
set -euo pipefail

BINARY="${BINARY:-$HOME/.cargo/bin/balerion}"
UNIT_DIR="$HOME/.config/systemd/user"
CONF_DIR="$HOME/.config/balerion"
ENV_FILE="$CONF_DIR/serve.env"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ ! -x "$BINARY" ]; then
  echo "no balerion binary at $BINARY" >&2
  echo "either 'cargo install --path crates/balerion-cli' or set BINARY=..." >&2
  exit 1
fi

# ffmpeg is optional to the program and not optional to the point of this
# exercise: without it, anything that is not already MP4 is offered as a
# download rather than played, and most of what you will want to watch is MKV.
if ! command -v ffmpeg >/dev/null 2>&1; then
  echo "warning: no ffmpeg on PATH." >&2
  echo "         MKV and similar will be offered as downloads rather than played." >&2
  echo "         apt install ffmpeg  (or your distribution's equivalent)" >&2
fi

# Prefer the Tailscale address to 0.0.0.0. On a laptop that is the difference
# between "my own devices can reach it" and "everyone on this network can try",
# and it means the token is a second line rather than the only one.
HOST="${BALERION_HOST:-}"
if [ -z "$HOST" ]; then
  if command -v tailscale >/dev/null 2>&1; then
    HOST="$(tailscale ip -4 2>/dev/null | head -1 || true)"
  fi
  HOST="${HOST:-0.0.0.0}"
fi

# The data directories too, and before the unit starts: systemd's
# ReadWritePaths refuses to start a service whose paths do not exist, and says
# so in terms that sound like the binary is missing.
mkdir -p "$UNIT_DIR" "$CONF_DIR" "$HOME/.cache/balerion" "$HOME/.local/share/balerion"

# A token that survives restarts, so the link on a phone keeps working. Kept in
# a file of its own, readable only by you, so the unit can be committed and read
# without carrying a credential.
if [ -f "$ENV_FILE" ] && grep -q '^BALERION_TOKEN=' "$ENV_FILE"; then
  echo "keeping the existing token in $ENV_FILE"
  TOKEN="$(grep '^BALERION_TOKEN=' "$ENV_FILE" | cut -d= -f2-)"
else
  TOKEN="$(head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
fi

umask 077
cat > "$ENV_FILE" <<EOF
# Read by balerion-serve.service. Generated by install-player-linux.sh.
#
# The token is required of every request that did not come from this machine.
# Anyone holding it can make this machine download things and delete what you
# are watching, so it is a credential rather than a setting.
BALERION_HOST=$HOST
BALERION_TOKEN=$TOKEN
EOF

install -m 644 "$HERE/balerion-serve.service" "$UNIT_DIR/balerion-serve.service"

systemctl --user daemon-reload
# A unit left in `failed` from an earlier attempt refuses to start again until
# its counter is cleared, and reports "Start request repeated too quickly",
# which reads as a crash loop rather than as stale state.
systemctl --user reset-failed balerion-serve 2>/dev/null || true
systemctl --user enable balerion-serve
systemctl --user restart balerion-serve

# So it keeps running when you are not logged in, which on an always-on machine
# is the entire point. Needs no password if it has been granted before.
if command -v loginctl >/dev/null 2>&1; then
  loginctl enable-linger "$USER" 2>/dev/null ||
    echo "note: could not enable lingering; the player will stop when you log out." >&2
fi

# Print the name rather than the number when there is one, because the cookie
# the gate sets belongs to the host that set it. Open the link by IP and then
# follow anything that spells the same machine by name and you arrive as a
# stranger, holding a token filed under the other spelling. The search site
# links by name, so the name is what has to be let in.
REACH="$HOST"
if command -v tailscale >/dev/null 2>&1; then
  # `--peers=false` so the only DNSName in the document is this machine's;
  # with peers in it the ordering is not something to rely on.
  NAME="$(tailscale status --json --peers=false 2>/dev/null |
    sed -n 's/.*"DNSName"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)"
  NAME="${NAME%.}"
  [ -n "$NAME" ] && REACH="$NAME"
fi

echo
echo "balerion-serve is running, bound to $HOST"
echo
echo "Open this once on each device that should be allowed in:"
echo
echo "  http://$REACH:8080/?balerion_token=$TOKEN"
echo
echo "It sets a cookie for a year, for that spelling of this machine only."
echo "Point the search site's BALERION_LOCAL_URL at http://$REACH:8080"
echo
echo "  systemctl --user status balerion-serve     what it is doing"
echo "  journalctl --user -u balerion-serve -f     what it is saying"
